### ISSUE TITLE
템플릿 변경 안하고 그대로 따라했을 때 발생한 에러

### ISSUE THREAD

**Issue by jjicjjjic** [jjicjjjic/mobilex_practice_team_25#1]
1.  steamlit을 설치하려 하자,
root@DESKTOP-O6G622T:~/mobilex_practice_team_25/Frontend# pip install streamlit
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

위와 같은 에러 발생(우리의 코드에서도 나타났던 에러)

-> 파이선 가상환경 만들어서 그 내에서 steamlit 설치

2. 디버그 후, steamlit 실행하니까 예시 피피티와는 조금 다르게 

(venv) root@DESKTOP-O6G622T:~/mobilex_practice_team_25/Frontend# streamlit run 0_Home.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.26.43.34:8501

gio: http://localhost:8501: Operation not supported

라고 나왔지만, link를 얻음

3.  해당 페이지에 들어가보니

2024-06-07 13:20:28.939 Uncaught app exception
Traceback (most recent call last):
  File "/root/mobilex_practice_team_25/Frontend/venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/root/mobilex_practice_team_25/Frontend/0_Home.py", line 4, in <module>
    from utils.init import init_once
  File "/root/mobilex_practice_team_25/Frontend/utils/init.py", line 2, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
2024-06-07 13:20:57.316 Uncaught app exception
Traceback (most recent call last):
  File "/root/mobilex_practice_team_25/Frontend/venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/root/mobilex_practice_team_25/Frontend/0_Home.py", line 4, in <module>
    from utils.init import init_once
  File "/root/mobilex_practice_team_25/Frontend/utils/init.py", line 2, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'

위와 같은 에러가 발생
템플릿 코드에서 변경한 사항은 하나도 없음

![KakaoTalk_20240607_132128419](https://github.com/jjicjjjic/mobilex_practice_team_25/assets/121376554/93875aa0-20e7-4421-8761-96552a884d93)

첨부한 사진은 steamlit을 실행했을 때 페이지 화면이다.

**Comment by jjicjjjic** [comment]
4. dotenv, pydantic_settings, httpx 를 가상환경 내에서 설치했으나,

AttributeError: module 'i18n' has no attribute 'load_path'

문제에서 막힘.

![load_path 문제 해결책 제안(챗지피티)](https://github.com/jjicjjjic/mobilex_practice_team_25/assets/121376554/af54f17a-3892-4772-a799-10935649afa5)
챗지피티에 따르면, 위와 같이 코드를 수정해야한다고 함
